# For other django project you should change 
# all occurrence 'menu' in: 
# 1. compose.yml (this file)
# 2.1 django/Dockerfile
# 2.2 django/uwsgi.ini
# 3.1 nginx/Dockerfile
# 3.2 nginx/nginx.conf
# 3.3 nginx/django.nginx.conf
version: "3.9"
services:
  nginx:
    build: ./nginx/
    restart: always
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/var/www/menu/assets/:ro
    ports:
# 8000:80
      - "80:8000"
    depends_on:
      - django

  django:
    build: ./django/
    restart: always
    command: >
      sh -c "python3 manage.py collectstatic --noinput
      && uwsgi --ini uwsgi.ini"
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/code/static/
      - web_static:/var/www/menu/assets/
      - ./www/:/code/www:ro
      - ./env/:/code/env:ro
volumes:
  uwsgi_data:
  web_static:

