# Generated by Django 4.1.7 on 2023-04-16 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dish", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="composition",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dish.dish"
            ),
        ),
        migrations.AddField(
            model_name="composition",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dish.ingredient"
            ),
        ),
        migrations.AddField(
            model_name="composition",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dish.unit"
            ),
        ),
    ]
