# Generated by Django 4.1.7 on 2023-04-14 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_user_delete_profile"),
        ("dish", "0002_alter_dish_user_alter_ingredient_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="user.user"
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="user.user"
            ),
        ),
    ]
