# Generated by Django 4.1.7 on 2023-04-18 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dish", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="fat",
            new_name="fats",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="protein",
            new_name="proteins",
        ),
    ]
