# Generated by Django 4.1.7 on 2023-04-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dish", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="value",
        ),
        migrations.AddField(
            model_name="unit",
            name="description",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
