# Generated by Django 4.1.7 on 2023-04-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dish", "0003_remove_unit_value_unit_description_alter_unit_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.CharField(blank=True, default="", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="description",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
    ]
