version: "3.9"
services:
  nginx:
    build: ./nginx/
    restart: always
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/var/www/menu/assets/:ro
    ports:
      - "8000:80"
    depends_on:
      - django

  django:
    build: ./web/
    restart: always
    command: >
      sh -c "python3 manage.py collectstatic --noinput
      && uwsgi --ini menu.uwsgi.ini"
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/code/static/
      - web_static:/var/www/menu/assets/
volumes:
  uwsgi_data:
  web_static:

