# Generated by Django 4.1.7 on 2023-04-18 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("filter", "0001_initial"),
        ("dish", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dish.dish"
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="dish.dish"
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "dish")},
        ),
    ]
