# Generated by Django 4.1.7 on 2023-04-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="icon",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
    ]
