# Generated by Django 4.1.7 on 2023-04-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=100, unique=True, verbose_name="email address"
            ),
        ),
    ]
