# Generated by Django 4.1.7 on 2023-04-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filter", "0003_alter_calendar_user_alter_like_user_and_more"),
        ("dish", "0002_alter_dish_user_alter_ingredient_user"),
        ("user", "0002_alter_auth_jwt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("icon", models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name="Auth",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
