# Generated by Django 4.1.7 on 2023-04-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_profile_delete_auth_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("icon", models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
