# Generated by Django 4.1.7 on 2023-04-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dish", "0003_rename_fat_ingredient_fats_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vitamin",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
            ],
        ),
    ]
