# Generated by Django 4.1.7 on 2023-04-28 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dish", "0004_vitamin"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="created",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="created",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
